### ISSUE TITLE
Very small console text on large resoltions

### ISSUE THREAD

**Issue by Robmonster** [Hyper-Dragon/DgtAngel#16]
Hi there,

In my initial testing I have fond the console text to be very small, I have linked a screenshot of my desktop with icons and LiveChess shown for comparison.  This laptop does have a high resolution, but all other windows features seem to scale.

https://i.imgur.com/Fpy6F5i.jpeg
https://i.imgur.com/p2ADl3C.png

**Comment by Hyper-Dragon** [comment]
Can't disagree...I should be able to change the console text easily enough with issue #18 . The rest of the form isn't so simple so I will create a separate enhancement when the console text is done.

**Comment by Hyper-Dragon** [comment]
Complete in ver 0.1.0
