### ISSUE TITLE
Didnt announce the move giving checkmate

### ISSUE THREAD

**Issue by Robmonster** [Hyper-Dragon/DgtAngel#17]
I just played a game, my opponent gave checkmate but the mate giving move wasn't announced. I was sat waiting for my opponents move when the game had actually finished. It wasnt until I glanced over at my PC screen that I realised the game was done

**Comment by Hyper-Dragon** [comment]
Guessing that the game was https://www.chess.com/game/live/31769446339?username=baronvonchickenpants

**Comment by Robmonster** [comment]
Yes, that was the game
