### ISSUE TITLE
Expanding your work for Offline-Play to create a versatile and configurable UCI-Engine for multi-platform (APP and OS) support 

### ISSUE THREAD

**Issue by Gunhawk007** [Hyper-Dragon/DgtAngel#28]
**Is your feature request related to a problem? Please describe.**
It would be great to expand this work to also work together with Offline-Chess GUIs. Lichess is great but online only and there are a number of GUIs out there that would benefit from a connected eBoard as GUI device, but are not supported i.e. due to the lack of DGT drivers like on Mac OS - currently it is not possible to use GUIs like Hiarcs Chess Explorer on Mac OS with the DGT-LiveChess framework, which is the only one currently supported on Mac OS.

**Describe the solution you'd like**
Implementation-wise I am thinking to create a versatile UCI Chess Engine that could be compiled for any OS which then could interact as a wrapper between the natively installed GUI such as Hiarcs, Arena etc. and allows to pass-through the I/O to a real chess engine of user's choice so that this would allow someone to play with any GUI and engine while using the DGT-board as input and the virtual board by the GUI and/or sound as output.

**Describe alternatives you've considered**
Picochess has some support for Linux, put I am not able to get this to run on a Mac.

**Additional context**

**Comment by Hyper-Dragon** [comment]
Thanks for the feedback.  Unfortunately, this is out of scope for this project.  I don’t have access to a Mac so I have no way to build (I know it can be done with online servers) and then test.  Forks are of course welcome.  Also, I am extremely hesitant to connect any engine to this project as it is specifically for online play and I don’t think that would be a good look from a cheating perspective.  

I did have an idea at the back of my mind (for another project) to do something with the ‘virtual clock’ idea and a UCI engine connection.  Your bridge idea would be an interesting addition to look into for this (if ever I find the time).
