### ISSUE TITLE
Wording for Position mismatch if no move replayed

### ISSUE THREAD

**Issue by dlbbld** [Hyper-Dragon/DgtAngel#75]
The software says "Position mismatch" if one replays the opponent's move incorrectly or does not replay the opponent's move within the specified delay.

For the second case, that is a bit disturbing. That is because the message is like an error message. But sometimes, one is just too slow to replay the move within the delay.

A message like "Move not replayed" is more user-friendly when one did not replay any move within the specified delay.

One might also repeat the played move, like "Bishop c5 not replayed".

**Comment by Hyper-Dragon** [comment]
Agreed.  I will include the additional notification.

**Comment by Hyper-Dragon** [comment]
'Move Not Replayed' is used as alternative notification if the matcher only finds one difference on the board
