### ISSUE TITLE
Immediate Position mismatch message

### ISSUE THREAD

**Issue by dlbbld** [Hyper-Dragon/DgtAngel#76]
If one does not replay the opponent's move within the specified delay, or one replays a wrong move, the software says, "Position mismatch".

Example: One plays e4 on the board, the opponent replies with d5, but one replays e5 on the board instead. After the delay, the software says there is a position mismatch.

But if after the first move replay there is a position mismatch, it would be much better if the software immediately signals the position mismatch.

For further wrong replays, one must not repeat the message. It is fine (as is already the case) to only speak a message when the position is correct again.

**Comment by Hyper-Dragon** [comment]
Definitely a nice to have, but implementation could be tricky to implement.

Cherub does not really care about moves outside of voice announcements, only board positions.  That’s why you can get the board in sync by moving pieces in any order. 

While perfectly valid I need to give further consideration as to the best way to proceed.

**Comment by dlbbld** [comment]
In my opinion, a straightforward possibility is to query the moves from the board. I guess you use the WebSocket interface to speak with the board. The board also provides legal moves detection and sends them. So you can use the built-in legal move detection of the board. That will capture the majority of cases. Cases where the user makes illegal moves are not detected, but that is the minority of the cases.

**Comment by dlbbld** [comment]
A pseudo-code to immediately catch wrong move replay looks like the below. I hope it helps.

The opponent made the move m leading to position p. One needs to replay. Let's say there are the legal moves l1, l2, l3, ... leading to positions p1, p2, p3, ... So one needs to replay the correct one.

A: wait for a position
If the position is one of p1, p2, p3, ... go to A-legal; otherwise, go to A

A-legal: To cover sliding movements, wait for another position for a short time (like 0.5 seconds).
If no position comes within the specified time, go to A-done.
Otherwise, if it is one of p1, p2, p3, ... go to A-legal; otherwise, go to A.

A-done: One has received a legal position, say p3.
If p3 is the opponent's move, the replay is correct. Otherwise, the replay is wrong, and one can immediately issue a message.

**Comment by Hyper-Dragon** [comment]
Cherub does indeed use web sockets to speak with the board but not directly.  It talks to LiveChess in the same way that CDC does.

A connection is open on the socket and on every detected change it sends a JSON message:

```
"{\"response\":\"feed\",\"id\":3,\"param\":{\"serialnr\":\"99999\",\"flipped\":false,\"board\":\"1nbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR\"},\"time\":1654538158856}"
```

As far as I can tell no moves are sent, legal or otherwise.  These messages seem to be received at whatever the boards polling rate is.  You can see this in the console if you slide a piece slowly.

```
[20:04:43] Local board changed [1nbqkbnr/1ppppppp/2r5/p7/8/8/PPPPPPPP/RNBQKBNR]
[20:04:44] Local board changed [1nbqkbnr/1ppppppp/3r4/p7/8/8/PPPPPPPP/RNBQKBNR]
[20:04:45] Local board changed [1nbqkbnr/1ppppppp/4r3/p7/8/8/PPPPPPPP/RNBQKBNR]
[20:04:46] Local board changed [1nbqkbnr/1ppppppp/5r2/p7/8/8/PPPPPPPP/RNBQKBNR]
[20:04:47] Local board changed [1nbqkbnr/1ppppppp/6r1/p7/8/8/PPPPPPPP/RNBQKBNR]
[20:04:48] Local board changed [1nbqkbnr/1ppppppp/7r/p7/8/8/PPPPPPPP/RNBQKBNR]
```

The local board representation inside cherub is stateless atm.  To implement this would involve holding state for the local board and calculating valid moves, which is fine, but adds another layer of complexity.  It is certainly doable as an extension of the AngelHubService since this already has a mechanism for delayed processing of events.

I did have in my mind the possibly of implementing engine support so this isn’t exclusively for CDC.  This change would be required for that.  In the interests of getting the next release published I think this would be better added to the backlog/rolled up in an engine play mode?

**Comment by dlbbld** [comment]
Then you are already there. In the same way you subscribe to a feed delivering board changes, you can subscribe to a feed delivering moves.

In DGT LiveChess, you can click on the menu "Window" then "About DGT LiveChess", this will open the below URL, which holds the documentation (when DGT LiveChess is running) and excellent examples for using the feed:
http://localhost:1982/doc/index.html

The whole point is you can also directly connect to the WebSocket server http://localhost:1982.

ATM makes sense. You can use the DGT board move detection. You get a move and position matches, correctly replayed, otherwise not, and you can issue the message. That covers maybe 80% of the cases. Of course, please feel free to add it to the backlog, just ideas from my side.

**Comment by dlbbld** [comment]
In addition to the above, the typical situation is that one replays a wrong but otherwise legal move. For example, playing White, one replays d6 instead of e6, or Nf6 instead of Nc6. However, one does not accidentally replay an illegal move like Nb8b6. For this reason, it is enough to use the legal move detection of the DGT board. The procedure catches maybe 80% of the replay problems, which is perfectly fine for the user as feedback.

**Comment by dlbbld** [comment]
Thanks for all the work, looks like this is too "tricky", so closing it for now. If there is a genuine interest other users might mention it again.

**Comment by dlbbld** [comment]
Thanks for all the work, looks like this is too "tricky", so closing it for now. If there is a genuine interest other users might mention it again.
