### ISSUE TITLE
Must Chrome be in the foreground?

### ISSUE THREAD

**Issue by dlbbld** [Hyper-Dragon/DgtAngel#78]
If I start the game using Chrome but then put the Chrome window in the background, the Cherub client gets out of sync.

Example:
I play d4 on the DGT board and put Chrome in the background. Now, the opponent replies with d5. I replay d5 on the board and the move is sent to chess.com as I understand, but now the Cherub client tells me, "Position mismatch". Somehow now the Cherub client does not see the current position on chess.com. Must the Chrome window stay in the foreground, so the Cherub client sees the chess.com game?

![Chrome window not active 4](https://user-images.githubusercontent.com/62600114/171663607-c3f84ff3-f804-4522-9e23-8e1c504cf832.jpg)

**Comment by Hyper-Dragon** [comment]
This is linked to #66 Angel stops sending updates when monitor powers off.

While ok on my machine it does seem to be an issue.  The same problem occurs if the monitor turns off during a game.  A short-term workaround for this has already been implemented but I recognise further investigation is required.

**Comment by Hyper-Dragon** [comment]
Should be fixed as a side effect of the 'play' board changes in #122
